configfile: "config/config.yaml"

PREFIX = config["root_dir"]


rule all:
    input: PREFIX + "/output/panhandles_preprocessed.tsv"


rule select_intervals:
    input:
        genome_annotation_gtf = config["genome_annotation"],
        conserved_regions_table = config["conserved_regions"],
        excluded_regions_bed = config["excluded_regions"]
    output:
        intervals_df = PREFIX + "/data/conin_python_long_filtered_final.tsv"
    conda: "envs/py2preph.yaml"
    resources:
        mem_mb=6000,
        runtime=600
    shell: """
python workflow/scripts/PrePH/src/SelectIntervals.py -a {input.genome_annotation_gtf}  -c {input.conserved_regions_table} -r {input.excluded_regions_bed} -o $(dirname {output.intervals_df})
"""    


rule find_panhandles:
    input:
        intervals_df = PREFIX + "/data/conin_python_long_filtered_final.tsv",
        genome_fa = config["genome_fa"],
        genome_annotation_gtf = config["genome_annotation"],
    output:
        ph_table = PREFIX + "/output/panhandles_preprocessed.tsv"
    conda: "envs/py2preph.yaml"
    threads: 8
    resources:
        mem_mb=lambda wildcards, threads: threads * 6000,
        runtime=600
    shell: """
python workflow/scripts/PrePH/src/FindPanhandles.py -i {input.intervals_df} -g {input.genome_fa} -n {input.genome_annotation_gtf} -o $(dirname {output.ph_table}) -t {threads}
"""
